<?php

namespace PHPMaker2021\project3;

use Slim\Views\PhpRenderer;
use Slim\Csrf\Guard;
use Psr\Container\ContainerInterface;
use Monolog\Logger;
use Monolog\Handler\RotatingFileHandler;
use Doctrine\DBAL\Logging\LoggerChain;
use Doctrine\DBAL\Logging\DebugStack;

return [
    "cache" => function (ContainerInterface $c) {
        return new \Slim\HttpCache\CacheProvider();
    },
    "view" => function (ContainerInterface $c) {
        return new PhpRenderer("views/");
    },
    "flash" => function (ContainerInterface $c) {
        return new \Slim\Flash\Messages();
    },
    "audit" => function (ContainerInterface $c) {
        $logger = new Logger("audit"); // For audit trail
        $logger->pushHandler(new AuditTrailHandler("audit.log"));
        return $logger;
    },
    "log" => function (ContainerInterface $c) {
        $logger = new Logger("log");
        $logger->pushHandler(new RotatingFileHandler("log.log"));
        return $logger;
    },
    "sqllogger" => function (ContainerInterface $c) {
        $loggers = [];
        if (Config("DEBUG")) {
            $loggers[] = $c->get("debugstack");
        }
        return (count($loggers) > 0) ? new LoggerChain($loggers) : null;
    },
    "csrf" => function (ContainerInterface $c) {
        global $ResponseFactory;
        return new Guard($ResponseFactory, Config("CSRF_PREFIX"));
    },
    "debugstack" => \DI\create(DebugStack::class),
    "debugsqllogger" => \DI\create(DebugSqlLogger::class),
    "security" => \DI\create(AdvancedSecurity::class),
    "profile" => \DI\create(UserProfile::class),
    "language" => \DI\create(Language::class),
    "timer" => \DI\create(Timer::class),

    // Tables
    "appointment_block_slot" => \DI\create(AppointmentBlockSlot::class),
    "appointment_patienttypee" => \DI\create(AppointmentPatienttypee::class),
    "appointment_reminder" => \DI\create(AppointmentReminder::class),
    "appointment_scheduler" => \DI\create(AppointmentScheduler::class),
    "audittrail" => \DI\create(Audittrail::class),
    "bankbranches" => \DI\create(Bankbranches::class),
    "banktransferto" => \DI\create(Banktransferto::class),
    "billing_discount" => \DI\create(BillingDiscount::class),
    "billing_other_voucher" => \DI\create(BillingOtherVoucher::class),
    "billing_refund_voucher" => \DI\create(BillingRefundVoucher::class),
    "billing_type" => \DI\create(BillingType::class),
    "billing_voucher" => \DI\create(BillingVoucher::class),
    "deposit_account_head" => \DI\create(DepositAccountHead::class),
    "deposit_pettycash" => \DI\create(DepositPettycash::class),
    "depositdetails" => \DI\create(Depositdetails::class),
    "doctors" => \DI\create(Doctors::class),
    "employee" => \DI\create(Employee::class),
    "employee_address" => \DI\create(EmployeeAddress::class),
    "employee_document" => \DI\create(EmployeeDocument::class),
    "employee_email" => \DI\create(EmployeeEmail::class),
    "employee_has_degree" => \DI\create(EmployeeHasDegree::class),
    "employee_has_experience" => \DI\create(EmployeeHasExperience::class),
    "employee_role_job_description" => \DI\create(EmployeeRoleJobDescription::class),
    "employee_telephone" => \DI\create(EmployeeTelephone::class),
    "help" => \DI\create(Help::class),
    "hospital" => \DI\create(Hospital::class),
    "hospital_pharmacy" => \DI\create(HospitalPharmacy::class),
    "hospital_store" => \DI\create(HospitalStore::class),
    "ip_admission" => \DI\create(IpAdmission::class),
    "ivf" => \DI\create(Ivf::class),
    "ivf_agency" => \DI\create(IvfAgency::class),
    "ivf_art_summary" => \DI\create(IvfArtSummary::class),
    "ivf_donorsemendetails" => \DI\create(IvfDonorsemendetails::class),
    "ivf_embryology_chart" => \DI\create(IvfEmbryologyChart::class),
    "ivf_et_chart" => \DI\create(IvfEtChart::class),
    "ivf_follow_up_tracking" => \DI\create(IvfFollowUpTracking::class),
    "ivf_history_master" => \DI\create(IvfHistoryMaster::class),
    "ivf_mas_art_cycle" => \DI\create(IvfMasArtCycle::class),
    "ivf_mas_template_type" => \DI\create(IvfMasTemplateType::class),
    "ivf_mas_user_template" => \DI\create(IvfMasUserTemplate::class),
    "ivf_oocytedenudation" => \DI\create(IvfOocytedenudation::class),
    "ivf_oocytedenudation_stage" => \DI\create(IvfOocytedenudationStage::class),
    "ivf_otherprocedure" => \DI\create(IvfOtherprocedure::class),
    "ivf_outcome" => \DI\create(IvfOutcome::class),
    "ivf_ovum_pick_up_chart" => \DI\create(IvfOvumPickUpChart::class),
    "ivf_semenan_medication" => \DI\create(IvfSemenanMedication::class),
    "ivf_semenanalysisreport" => \DI\create(IvfSemenanalysisreport::class),
    "ivf_stimulation_chart" => \DI\create(IvfStimulationChart::class),
    "ivf_stimulation_gnrh" => \DI\create(IvfStimulationGnrh::class),
    "ivf_stimulation_hmg" => \DI\create(IvfStimulationHmg::class),
    "ivf_stimulation_inj" => \DI\create(IvfStimulationInj::class),
    "ivf_stimulation_rfsh" => \DI\create(IvfStimulationRfsh::class),
    "ivf_stimulation_tablet" => \DI\create(IvfStimulationTablet::class),
    "ivf_stimulation_trigger" => \DI\create(IvfStimulationTrigger::class),
    "ivf_treatment_plan" => \DI\create(IvfTreatmentPlan::class),
    "ivf_vitals_history" => \DI\create(IvfVitalsHistory::class),
    "ivf_vitrification" => \DI\create(IvfVitrification::class),
    "lab_dept_mast" => \DI\create(LabDeptMast::class),
    "lab_drug_mast" => \DI\create(LabDrugMast::class),
    "lab_mas_sampletype" => \DI\create(LabMasSampletype::class),
    "lab_profile_details" => \DI\create(LabProfileDetails::class),
    "lab_profile_master" => \DI\create(LabProfileMaster::class),
    "lab_sepcimen_mast" => \DI\create(LabSepcimenMast::class),
    "lab_test_master" => \DI\create(LabTestMaster::class),
    "lab_test_result" => \DI\create(LabTestResult::class),
    "lab_unit_mast" => \DI\create(LabUnitMast::class),
    "mas_activity_card" => \DI\create(MasActivityCard::class),
    "mas_billing_department" => \DI\create(MasBillingDepartment::class),
    "mas_bloodgroup" => \DI\create(MasBloodgroup::class),
    "mas_category" => \DI\create(MasCategory::class),
    "mas_clinicaldetails" => \DI\create(MasClinicaldetails::class),
    "mas_degree" => \DI\create(MasDegree::class),
    "mas_document" => \DI\create(MasDocument::class),
    "mas_employee_role_job_description" => \DI\create(MasEmployeeRoleJobDescription::class),
    "mas_job" => \DI\create(MasJob::class),
    "mas_lab_services_type" => \DI\create(MasLabServicesType::class),
    "mas_language" => \DI\create(MasLanguage::class),
    "mas_marital_status" => \DI\create(MasMaritalStatus::class),
    "mas_modepayment" => \DI\create(MasModepayment::class),
    "mas_payment_status" => \DI\create(MasPaymentStatus::class),
    "mas_paymentcategory" => \DI\create(MasPaymentcategory::class),
    "mas_pharmacy" => \DI\create(MasPharmacy::class),
    "mas_procedure" => \DI\create(MasProcedure::class),
    "mas_reference_type" => \DI\create(MasReferenceType::class),
    "mas_services_billing" => \DI\create(MasServicesBilling::class),
    "mas_services_type" => \DI\create(MasServicesType::class),
    "mas_template_prescription_type" => \DI\create(MasTemplatePrescriptionType::class),
    "mas_template_type" => \DI\create(MasTemplateType::class),
    "mas_typeofregsistration" => \DI\create(MasTypeofregsistration::class),
    "mas_user_template" => \DI\create(MasUserTemplate::class),
    "mas_user_template_prescription" => \DI\create(MasUserTemplatePrescription::class),
    "mas_where_didyou_hear" => \DI\create(MasWhereDidyouHear::class),
    "master_procedure_treatment" => \DI\create(MasterProcedureTreatment::class),
    "monitor_treatment_plan" => \DI\create(MonitorTreatmentPlan::class),
    "patient" => \DI\create(Patient::class),
    "patient_address" => \DI\create(PatientAddress::class),
    "patient_an_registration" => \DI\create(PatientAnRegistration::class),
    "patient_app" => \DI\create(PatientApp::class),
    "patient_document" => \DI\create(PatientDocument::class),
    "patient_email" => \DI\create(PatientEmail::class),
    "patient_emergency_contact" => \DI\create(PatientEmergencyContact::class),
    "patient_final_diagnosis" => \DI\create(PatientFinalDiagnosis::class),
    "patient_follow_up" => \DI\create(PatientFollowUp::class),
    "patient_history" => \DI\create(PatientHistory::class),
    "patient_insurance" => \DI\create(PatientInsurance::class),
    "patient_investigations" => \DI\create(PatientInvestigations::class),
    "patient_opd_follow_up" => \DI\create(PatientOpdFollowUp::class),
    "patient_ot_delivery_register" => \DI\create(PatientOtDeliveryRegister::class),
    "patient_ot_surgery_register" => \DI\create(PatientOtSurgeryRegister::class),
    "patient_prescription" => \DI\create(PatientPrescription::class),
    "patient_provisional_diagnosis" => \DI\create(PatientProvisionalDiagnosis::class),
    "patient_room" => \DI\create(PatientRoom::class),
    "patient_services" => \DI\create(PatientServices::class),
    "patient_telephone" => \DI\create(PatientTelephone::class),
    "patient_vitals" => \DI\create(PatientVitals::class),
    "pharmacy" => \DI\create(Pharmacy::class),
    "pharmacy_batchmas" => \DI\create(PharmacyBatchmas::class),
    "pharmacy_billing_issue" => \DI\create(PharmacyBillingIssue::class),
    "pharmacy_billing_return" => \DI\create(PharmacyBillingReturn::class),
    "pharmacy_billing_transfer" => \DI\create(PharmacyBillingTransfer::class),
    "pharmacy_billing_voucher" => \DI\create(PharmacyBillingVoucher::class),
    "pharmacy_comb_master" => \DI\create(PharmacyCombMaster::class),
    "pharmacy_combination" => \DI\create(PharmacyCombination::class),
    "pharmacy_customers" => \DI\create(PharmacyCustomers::class),
    "pharmacy_grn" => \DI\create(PharmacyGrn::class),
    "pharmacy_master_generic" => \DI\create(PharmacyMasterGeneric::class),
    "pharmacy_master_genericgrp" => \DI\create(PharmacyMasterGenericgrp::class),
    "pharmacy_master_mfr_master" => \DI\create(PharmacyMasterMfrMaster::class),
    "pharmacy_master_product_similar" => \DI\create(PharmacyMasterProductSimilar::class),
    "pharmacy_payment" => \DI\create(PharmacyPayment::class),
    "pharmacy_pharled" => \DI\create(PharmacyPharled::class),
    "pharmacy_po" => \DI\create(PharmacyPo::class),
    "pharmacy_products" => \DI\create(PharmacyProducts::class),
    "pharmacy_purchase_request" => \DI\create(PharmacyPurchaseRequest::class),
    "pharmacy_purchase_request_items" => \DI\create(PharmacyPurchaseRequestItems::class),
    "pharmacy_purchaseorder" => \DI\create(PharmacyPurchaseorder::class),
    "pharmacy_services" => \DI\create(PharmacyServices::class),
    "pharmacy_storemast" => \DI\create(PharmacyStoremast::class),
    "pharmacy_suppliers" => \DI\create(PharmacySuppliers::class),
    "pres_categoryallergy" => \DI\create(PresCategoryallergy::class),
    "pres_container_type" => \DI\create(PresContainerType::class),
    "pres_fluidformulation" => \DI\create(PresFluidformulation::class),
    "pres_fluids" => \DI\create(PresFluids::class),
    "pres_frequencies" => \DI\create(PresFrequencies::class),
    "pres_genericinteractions" => \DI\create(PresGenericinteractions::class),
    "pres_indicationstable" => \DI\create(PresIndicationstable::class),
    "pres_mas_forms" => \DI\create(PresMasForms::class),
    "pres_mas_generic" => \DI\create(PresMasGeneric::class),
    "pres_mas_route" => \DI\create(PresMasRoute::class),
    "pres_mas_status" => \DI\create(PresMasStatus::class),
    "pres_mas_timeoftaking" => \DI\create(PresMasTimeoftaking::class),
    "pres_mas_unit" => \DI\create(PresMasUnit::class),
    "pres_quantity" => \DI\create(PresQuantity::class),
    "pres_restricteddruglist" => \DI\create(PresRestricteddruglist::class),
    "pres_routes" => \DI\create(PresRoutes::class),
    "pres_sideeffect_table" => \DI\create(PresSideeffectTable::class),
    "pres_trade_combination_names" => \DI\create(PresTradeCombinationNames::class),
    "pres_trade_combination_names_new" => \DI\create(PresTradeCombinationNamesNew::class),
    "pres_tradenames" => \DI\create(PresTradenames::class),
    "pres_tradenames_new" => \DI\create(PresTradenamesNew::class),
    "receipts" => \DI\create(Receipts::class),
    "reception" => \DI\create(Reception::class),
    "room_master" => \DI\create(RoomMaster::class),
    "room_types" => \DI\create(RoomTypes::class),
    "sms_cintent" => \DI\create(SmsCintent::class),
    "sms_type" => \DI\create(SmsType::class),
    "store_batchmas" => \DI\create(StoreBatchmas::class),
    "store_intent_issue" => \DI\create(StoreIntentIssue::class),
    "store_storeled" => \DI\create(StoreStoreled::class),
    "store_storemast" => \DI\create(StoreStoremast::class),
    "store_suppliers" => \DI\create(StoreSuppliers::class),
    "sys_address_type" => \DI\create(SysAddressType::class),
    "sys_days" => \DI\create(SysDays::class),
    "sys_email_type" => \DI\create(SysEmailType::class),
    "sys_gender" => \DI\create(SysGender::class),
    "sys_status" => \DI\create(SysStatus::class),
    "sys_tele_type" => \DI\create(SysTeleType::class),
    "sys_telephone_type" => \DI\create(SysTelephoneType::class),
    "sys_tittle" => \DI\create(SysTittle::class),
    "task_management" => \DI\create(TaskManagement::class),
    "thaw" => \DI\create(Thaw::class),
    "user_login" => \DI\create(UserLogin::class),
    "userlevelpermissions" => \DI\create(Userlevelpermissions::class),
    "userlevels" => \DI\create(Userlevels::class),
    "view_activity_card" => \DI\create(ViewActivityCard::class),
    "view_appointment" => \DI\create(ViewAppointment::class),
    "view_appointment_scheduler" => \DI\create(ViewAppointmentScheduler::class),
    "view_appointment_scheduler_new" => \DI\create(ViewAppointmentSchedulerNew::class),
    "view_barcode_ivf" => \DI\create(ViewBarcodeIvf::class),
    "view_bill_collection_report" => \DI\create(ViewBillCollectionReport::class),
    "view_bill_collection_summary" => \DI\create(ViewBillCollectionSummary::class),
    "view_billing_transaction" => \DI\create(ViewBillingTransaction::class),
    "view_billing_voucher" => \DI\create(ViewBillingVoucher::class),
    "view_billing_voucher_print" => \DI\create(ViewBillingVoucherPrint::class),
    "view_billing_voucher_voucher" => \DI\create(ViewBillingVoucherVoucher::class),
    "view_dash_billing_voucher" => \DI\create(ViewDashBillingVoucher::class),
    "view_dashboard_collection_details" => \DI\create(ViewDashboardCollectionDetails::class),
    "view_dashboard_patient_details" => \DI\create(ViewDashboardPatientDetails::class),
    "view_dashboard_patient_summary" => \DI\create(ViewDashboardPatientSummary::class),
    "view_dashboard_service_count" => \DI\create(ViewDashboardServiceCount::class),
    "view_dashboard_service_details" => \DI\create(ViewDashboardServiceDetails::class),
    "view_dashboard_service_drwise_summary" => \DI\create(ViewDashboardServiceDrwiseSummary::class),
    "view_dashboard_service_servicetype" => \DI\create(ViewDashboardServiceServicetype::class),
    "view_dashboard_service_summary" => \DI\create(ViewDashboardServiceSummary::class),
    "view_dashboard_summary_details" => \DI\create(ViewDashboardSummaryDetails::class),
    "view_dashboard_summary_modeofpayment_details" => \DI\create(ViewDashboardSummaryModeofpaymentDetails::class),
    "view_dashboard_summary_payment_mode" => \DI\create(ViewDashboardSummaryPaymentMode::class),
    "view_delivery_registered" => \DI\create(ViewDeliveryRegistered::class),
    "view_doctor_notes" => \DI\create(ViewDoctorNotes::class),
    "view_donor_ivf" => \DI\create(ViewDonorIvf::class),
    "view_donor_semen_stock" => \DI\create(ViewDonorSemenStock::class),
    "view_duplicate_patientid" => \DI\create(ViewDuplicatePatientid::class),
    "view_et" => \DI\create(ViewEt::class),
    "view_find_diff_bills" => \DI\create(ViewFindDiffBills::class),
    "view_follow_up" => \DI\create(ViewFollowUp::class),
    "view_follow_up_tracking" => \DI\create(ViewFollowUpTracking::class),
    "view_followups" => \DI\create(ViewFollowups::class),
    "view_gst_output" => \DI\create(ViewGstOutput::class),
    "view_icsi_advised" => \DI\create(ViewIcsiAdvised::class),
    "view_ip_admission" => \DI\create(ViewIpAdmission::class),
    "view_ip_admission_bill_summary" => \DI\create(ViewIpAdmissionBillSummary::class),
    "view_ip_admission_issue" => \DI\create(ViewIpAdmissionIssue::class),
    "view_ip_admission_prescription" => \DI\create(ViewIpAdmissionPrescription::class),
    "view_ip_admission_services" => \DI\create(ViewIpAdmissionServices::class),
    "view_ip_advance" => \DI\create(ViewIpAdvance::class),
    "view_ip_billing" => \DI\create(ViewIpBilling::class),
    "view_ip_patient_admission" => \DI\create(ViewIpPatientAdmission::class),
    "view_issuing_semen" => \DI\create(ViewIssuingSemen::class),
    "view_item_received" => \DI\create(ViewItemReceived::class),
    "view_iui_excel" => \DI\create(ViewIuiExcel::class),
    "view_ivf_treatment" => \DI\create(ViewIvfTreatment::class),
    "view_ivf_treatment_plan" => \DI\create(ViewIvfTreatmentPlan::class),
    "view_lab_print" => \DI\create(ViewLabPrint::class),
    "view_lab_profile" => \DI\create(ViewLabProfile::class),
    "view_lab_resultreleased" => \DI\create(ViewLabResultreleased::class),
    "view_lab_resultreleased_auth" => \DI\create(ViewLabResultreleasedAuth::class),
    "view_lab_resultreleasedd" => \DI\create(ViewLabResultreleasedd::class),
    "view_lab_service" => \DI\create(ViewLabService::class),
    "view_lab_service_sub" => \DI\create(ViewLabServiceSub::class),
    "view_lab_services" => \DI\create(ViewLabServices::class),
    "view_lab_services_auth" => \DI\create(ViewLabServicesAuth::class),
    "view_lab_servicess" => \DI\create(ViewLabServicess::class),
    "view_labreport_print" => \DI\create(ViewLabreportPrint::class),
    "view_next_review_date" => \DI\create(ViewNextReviewDate::class),
    "view_ongoing_treatment" => \DI\create(ViewOngoingTreatment::class),
    "view_opd_follow_up" => \DI\create(ViewOpdFollowUp::class),
    "view_partner_semenstock" => \DI\create(ViewPartnerSemenstock::class),
    "view_patient_billing" => \DI\create(ViewPatientBilling::class),
    "view_patient_clinical_summary" => \DI\create(ViewPatientClinicalSummary::class),
    "view_patient_discharge_summary" => \DI\create(ViewPatientDischargeSummary::class),
    "view_patient_discharge_summary_group" => \DI\create(ViewPatientDischargeSummaryGroup::class),
    "view_patient_history" => \DI\create(ViewPatientHistory::class),
    "view_patient_services" => \DI\create(ViewPatientServices::class),
    "view_patient_services_dashboard" => \DI\create(ViewPatientServicesDashboard::class),
    "view_patient_vitals" => \DI\create(ViewPatientVitals::class),
    "view_pharmacy_consumption" => \DI\create(ViewPharmacyConsumption::class),
    "view_pharmacy_movement" => \DI\create(ViewPharmacyMovement::class),
    "view_pharmacy_movement_item" => \DI\create(ViewPharmacyMovementItem::class),
    "view_pharmacy_pharled_return" => \DI\create(ViewPharmacyPharledReturn::class),
    "view_pharmacy_purchase_request_approved" => \DI\create(ViewPharmacyPurchaseRequestApproved::class),
    "view_pharmacy_purchase_request_items_approved" => \DI\create(ViewPharmacyPurchaseRequestItemsApproved::class),
    "view_pharmacy_purchase_request_items_purchased" => \DI\create(ViewPharmacyPurchaseRequestItemsPurchased::class),
    "view_pharmacy_purchase_request_purchased" => \DI\create(ViewPharmacyPurchaseRequestPurchased::class),
    "view_pharmacy_sales" => \DI\create(ViewPharmacySales::class),
    "view_pharmacy_search_product" => \DI\create(ViewPharmacySearchProduct::class),
    "view_pharmacy_search_product_new" => \DI\create(ViewPharmacySearchProductNew::class),
    "view_pharmacygrn" => \DI\create(ViewPharmacygrn::class),
    "view_pharmacytransfer" => \DI\create(ViewPharmacytransfer::class),
    "view_procedure_registered" => \DI\create(ViewProcedureRegistered::class),
    "view_semenanalysis" => \DI\create(ViewSemenanalysis::class),
    "view_till_search" => \DI\create(ViewTillSearch::class),
    "view_till_search_view" => \DI\create(ViewTillSearchView::class),
    "view_treatmend_status" => \DI\create(ViewTreatmendStatus::class),
    "view_treatment_culture" => \DI\create(ViewTreatmentCulture::class),

    // Detail table pages
];
